import assert from "node:assert/strict"
import fs from "node:fs"
import path from "node:path"
import { test } from "node:test"

const rootDir = path.resolve(import.meta.dirname, "..")

test("semantic palette helpers and style audit baseline are wired", () => {
  const paletteSource = readProjectFile("apps/web/src/render/shared/canvas-palette.ts")
  const tokensSource = readProjectFile("apps/web/src/styles/tokens.css")
  const baseSource = readProjectFile("apps/web/src/styles/base.css")
  const auditSource = readProjectFile("tools/style-audit.mjs")
  const baseline = JSON.parse(readProjectFile("tools/style-audit/direct-color-baseline.json"))

  assert.match(tokensSource, /--color-void-depth:\s*#0a1628;/)
  assert.match(baseSource, /--mg-deep:\s*var\(--color-void-depth\)/)
  assert.match(paletteSource, /export function hex/)
  assert.match(paletteSource, /export function rgba/)
  assert.match(paletteSource, /export function gradientStop/)
  assert.match(paletteSource, /export function resolveGlow/)
  for (const cssVar of new Set([...paletteSource.matchAll(/cssVar: "(--[^"]+)"/g)].map((match) => match[1]))) {
    assert.match(tokensSource, new RegExp(`${escapeRegExp(cssVar)}\\s*:`))
  }
  assert.match(auditSource, /direct color literals are not allowed in new baseline files/)
  assert.match(auditSource, /red threatNoise-like literals increased/)
  assert.equal(baseline.source, "apps/web/src")
  assert.ok(Object.keys(baseline.files).length > 0)
})

test("shared canvas effects expose phase 1 rendering entry points", () => {
  const effectsIndex = readProjectFile("apps/web/src/render/shared/effects/index.ts")
  const scanPulseSource = readProjectFile("apps/web/src/render/explore/scan-pulse.ts")
  const battlePresentationSource = readProjectFile("apps/web/src/render/battle/presentation-layer.ts")

  assert.match(effectsIndex, /signal-pulse/)
  assert.match(effectsIndex, /residual-fragment/)
  assert.match(effectsIndex, /threat-noise-field/)
  assert.match(effectsIndex, /artificial-grid/)
  assert.match(effectsIndex, /surface-frame/)
  assert.match(scanPulseSource, /drawSignalPulse/)
  assert.match(scanPulseSource, /computeMaxVisiblePulseRadius/)
  assert.match(scanPulseSource, /radius > maxVisibleRadius/)
  assert.match(battlePresentationSource, /drawThreatNoiseField/)
  assert.match(battlePresentationSource, /drawResidualFragment/)
})

test("battle renderers consume preset motion, palette, and subtitle spans", () => {
  const enemyRendererSource = readProjectFile("apps/web/src/render/battle/enemies/enemy-renderer.ts")
  const hazardRendererSource = readProjectFile("apps/web/src/render/battle/hazards/magnetic-disaster.ts")
  const battleScreenSource = readProjectFile("apps/web/src/screens/battle/BattleScreen.tsx")
  const battleStyleSource = readProjectFile("apps/web/src/styles/battle.css")

  assert.match(enemyRendererSource, /readEnemyMotionProfile\(enemy\.visual\.motionProfile\)/)
  assert.match(hazardRendererSource, /readHazardPaletteRole\(hazard\.visual\.paletteRole\)/)
  assert.match(hazardRendererSource, /drawThreatNoiseField/)
  assert.match(battleScreenSource, /protectedSpans/)
  assert.match(battleScreenSource, /damagedSpans/)
  assert.match(battleScreenSource, /waveInterference/)
  assert.match(battleScreenSource, /renderSubtitleProtectionSegments/)
  assert.match(battleScreenSource, /readSubtitleCorruptionVariant/)
  assert.match(battleScreenSource, /readWaveInterferenceDensity/)
  assert.match(battleScreenSource, /"mask" \| "mojibake" \| "scramble" \| "glitch"/)
  assert.match(battleStyleSource, /subtitle-corrupt--glitch/)
  assert.match(battleStyleSource, /subtitle-wave--readable/)
})

test("pointer and overlay input edges are not carried into explore", () => {
  const inputSource = readProjectFile("apps/web/src/app/use-magnolia-input.ts")
  const frameLoopSource = readProjectFile("apps/web/src/app/frame-loop/use-magnolia-frame-loop.ts")

  assert.match(inputSource, /const supportsPointerEvents = "PointerEvent" in window/)
  assert.match(inputSource, /window\.addEventListener\("pointerdown", handlePointerDown, true\)/)
  assert.match(inputSource, /window\.addEventListener\("mousedown", handleMouseDown, true\)/)

  const contextMenuHandler = inputSource.match(/function handleContextMenu[\s\S]*?\n    }/)?.[0] ?? ""
  assert.match(contextMenuHandler, /event\.preventDefault\(\)/)
  assert.doesNotMatch(contextMenuHandler, /queueMouseButtonPress/)
  assert.doesNotMatch(contextMenuHandler, /releaseMouseButton/)

  assert.match(frameLoopSource, /snapshot\.screen === "explore" && appState\.equipmentModalNodeId[\s\S]*?input\.syncButtonEdges\(settings\)/)
})

test("presentation requests reach battle and transition renderers", () => {
  const hookSource = readProjectFile("apps/web/src/app/use-magnolia-app.ts")
  const sessionSyncSource = readProjectFile("apps/web/src/app/session-sync.ts")
  const appSource = readProjectFile("apps/web/src/app/App.tsx")
  const exploreScreenSource = readProjectFile("apps/web/src/screens/explore/ExploreScreen.tsx")
  const exploreMapStyleSource = readProjectFile("apps/web/src/styles/explore-map.css")
  const battleScreenSource = readProjectFile("apps/web/src/screens/battle/BattleScreen.tsx")
  const battleCanvasSource = readProjectFile("apps/web/src/render/battle/BattleCanvas.tsx")
  const drawBattleFrameSource = readProjectFile("apps/web/src/render/battle/draw-battle-frame.ts")
  const battlePresentationSource = readProjectFile("apps/web/src/render/battle/presentation-layer.ts")
  const transitionLayerSource = readProjectFile("apps/web/src/app/presentation/TransitionPresentationLayer.tsx")

  assert.match(sessionSyncSource, /drainPresentationRequests\(\)/)
  assert.match(hookSource, /selectBattlePresentationEvents/)
  assert.match(hookSource, /selectTransitionPresentationEvents/)
  assert.match(appSource, /battleEvents=\{app\.battleEvents\}/)
  assert.match(battleScreenSource, /battleEvents=\{battleEvents\}/)
  assert.match(battleCanvasSource, /battleEvents,\s*\n/)
  assert.match(drawBattleFrameSource, /drawBattlePresentationLayer/)
  assert.match(battlePresentationSource, /case "battle\.player\.hit":/)
  assert.match(appSource, /<TransitionPresentationLayer[\s\S]*?events=\{app\.transitionEvents\}/)
  assert.match(transitionLayerSource, /transmission\.connect\.sequence/)
  assert.match(exploreScreenSource, /presentation\.kind === "release"[\s\S]*?pendingSignalGuideReleaseIdRef\.current = presentation\.requestId/)
  assert.match(exploreScreenSource, /SIGNAL HUD/)
  assert.match(exploreScreenSource, /click 2[\s\S]*?右クリック/)
  assert.match(exploreScreenSource, /赤は mission や通信反応/)
  assert.match(exploreScreenSource, /青白い円が現在の視界範囲/)
  assert.match(exploreMapStyleSource, /\.signal-guide-popup/)
})

test("title save slots treat slot 1 and zero play time profiles as empty", () => {
  const hookSource = readProjectFile("apps/web/src/app/use-magnolia-app.ts")
  const saveSlotSelectorsSource = readProjectFile("apps/web/src/app/save-slot-selectors.ts")
  const actionsSource = readProjectFile("apps/web/src/app/magnolia-actions.ts")
  const audioEventsSource = readProjectFile("apps/web/src/audio/audioEvents.ts")
  const audioHubSource = readProjectFile("apps/web/src/audio/AudioHub.ts")
  const audioAdapterSource = readProjectFile("apps/web/src/app/audio-event-adapter.ts")
  const titleScreenSource = readProjectFile("apps/web/src/screens/title/TitleScreen.tsx")
  const titleStyleSource = readProjectFile("apps/web/src/styles/title.css")

  assert.match(saveSlotSelectorsSource, /function isTitleSaveSlotEmpty/)
  assert.match(saveSlotSelectorsSource, /slot\.slotId === 1[\s\S]*?return true/)
  assert.match(saveSlotSelectorsSource, /return !slot\.profileId \|\| slot\.playTimeMs <= 0/)
  assert.match(hookSource, /updatedAt: isEmpty \? undefined : formatTimestamp\(slot\.updatedAt\)/)
  assert.match(hookSource, /!isEmpty && slot\.currentAreaId/)
  assert.match(titleScreenSource, /title-click-ripple/)
  assert.match(titleScreenSource, /emitRippleFromElement/)
  assert.match(titleScreenSource, /TITLE_UI_SOUND_VOLUME/)
  assert.match(titleScreenSource, /soundVolume: TITLE_UI_SOUND_VOLUME/)
  assert.match(titleStyleSource, /@keyframes title-click-ripple/)
  assert.match(titleScreenSource, /minMs: 18000,\s*\n\s*maxMs: 32000/)
  assert.match(titleScreenSource, /minMs: 36000,\s*\n\s*maxMs: 66000/)
  assert.match(titleScreenSource, /Math\.random\(\) \* Math\.max\(0, input\.maxMs - input\.minMs\)/)
  assert.match(titleScreenSource, /setDeparting\(true\)[\s\S]*?onConfirmSlot\(slot\.slotId\)/)
  assert.match(titleScreenSource, /label: "debug mode"[\s\S]*?onStartDebugMode\(\)/)
  assert.doesNotMatch(titleScreenSource, /label: "exit"/)
  assert.match(titleScreenSource, /title-curtain--active/)
  assert.match(actionsSource, /await waitForTitleConfirmCue[\s\S]*?startNewGameAtSlot/)
  assert.match(actionsSource, /await waitForTitleConfirmCue[\s\S]*?resumeSaveSlot/)
  assert.match(actionsSource, /audioEvents\.uiOpen\(\{ volume: TITLE_UI_SOUND_VOLUME \}\)/)
  assert.match(actionsSource, /audioEvents\.uiClose\(\{ volume: TITLE_UI_SOUND_VOLUME \}\)/)
  assert.match(actionsSource, /async startDebugMode\(\)[\s\S]*?type: "startDebugMode"/)
  assert.match(audioEventsSource, /export const TITLE_UI_SOUND_VOLUME = 1\.25/)
  assert.match(audioEventsSource, /menuMove\(direction: MenuDirection = 'down', options\?: PlaySoundOptions\)/)
  assert.match(audioEventsSource, /menuConfirm\(options\?: PlaySoundOptions\)/)
  assert.match(audioEventsSource, /playAndWait\(SOUND_KEYS\.TITLE_NEW_GAME/)
  assert.match(audioEventsSource, /playAndWait\(SOUND_KEYS\.TITLE_LOAD_GAME/)
  assert.match(audioEventsSource, /TITLE_CONFIRM_TRANSITION_WAIT_MS = 1000/)
  assert.match(audioEventsSource, /minimumWaitMs: TITLE_CONFIRM_TRANSITION_WAIT_MS/)
  assert.match(audioEventsSource, /maxWaitMs: TITLE_CONFIRM_TRANSITION_WAIT_MS/)
  assert.match(audioHubSource, /playAndWait\(key: SoundKey, options: PlaySoundAndWaitOptions = \{\}\): Promise<void>/)
  assert.match(audioHubSource, /audio\.addEventListener\('ended', complete/)
  assert.match(audioAdapterSource, /if \(!previousScreen\) \{[\s\S]*?nextSnapshot\.screen === "title"[\s\S]*?audioEvents\.titleOpened\(\)/)
  assert.match(audioAdapterSource, /previousScreen === "title"[\s\S]*?audioEvents\.uiOpen\(\{ volume: TITLE_UI_SOUND_VOLUME \}\)/)
  assert.match(audioAdapterSource, /nextSnapshot\.screen === "title" \? \{ volume: TITLE_UI_SOUND_VOLUME \} : undefined/)
  assert.match(audioAdapterSource, /previousScreen === "title" && nextSnapshot\.screen === "explore"[\s\S]*?audioEvents\.explorationEntered/)
  assert.match(audioEventsSource, /reconstructionStarted\(\): void \{[\s\S]*?audioHub\.play\(SOUND_KEYS\.SYSTEM_RECONSTRUCT\)/)
})

test("battle and explore renderers share basic render math", () => {
  const sharedMath = readProjectFile("apps/web/src/render/shared/render-math.ts")
  const battleUtils = readProjectFile("apps/web/src/render/battle/battle-renderer-utils.ts")
  const exploreUtils = readProjectFile("apps/web/src/render/explore/explore-render-utils.ts")

  assert.match(sharedMath, /export const TAU = Math\.PI \* 2/)
  assert.match(sharedMath, /export function easeOutCubic/)
  assert.match(sharedMath, /export function seededUnit/)
  assert.match(battleUtils, /from "@\/render\/shared\/render-math"/)
  assert.match(exploreUtils, /from "@\/render\/shared\/render-math"/)
})

test("idle auto save warns, cancels on input, and skips title", () => {
  const idleAutoSaveSource = readProjectFile("apps/web/src/app/idle-auto-save.ts")
  const saveSlotSelectorsSource = readProjectFile("apps/web/src/app/save-slot-selectors.ts")
  const inputSource = readProjectFile("apps/web/src/app/use-magnolia-input.ts")
  const appSource = readProjectFile("apps/web/src/app/App.tsx")
  const actionsSource = readProjectFile("apps/web/src/app/magnolia-actions.ts")
  const settingsPanelSource = readProjectFile("apps/web/src/screens/menu/SettingsPanel.tsx")

  assert.match(idleAutoSaveSource, /IDLE_AUTO_SAVE_WARNING_AFTER_MS = 50_000/)
  assert.match(idleAutoSaveSource, /IDLE_AUTO_SAVE_COUNTDOWN_MS = 10_000/)
  assert.match(idleAutoSaveSource, /snapshot\.screen === "title"[\s\S]*?current\.slotSelectMode/)
  assert.match(idleAutoSaveSource, /input\.getLastActivityAt\(\) > countdown\.startedAt/)
  assert.match(idleAutoSaveSource, /selectIdleAutoSaveSlot\(snapshot\.saveSlots\.slots\)/)
  assert.match(idleAutoSaveSource, /dispatchManyAndSync/)
  assert.match(saveSlotSelectorsSource, /PROGRESS_SAVE_SLOT_IDS: readonly SaveSlotId\[] = \[2, 3\]/)
  assert.match(saveSlotSelectorsSource, /function listProgressSaveSlots/)
  assert.match(saveSlotSelectorsSource, /slots\.filter\(\(slot\) => isProgressSaveSlotId\(slot\.slotId\)\)/)
  assert.match(saveSlotSelectorsSource, /const progressSlots = listProgressSaveSlots\(slots\)/)
  assert.match(saveSlotSelectorsSource, /progressSlots\.find\(\(slot\) => isTitleSaveSlotEmpty\(slot\)\)/)
  assert.match(saveSlotSelectorsSource, /readSlotUpdatedAtMs\(left\.updatedAt\) - readSlotUpdatedAtMs\(right\.updatedAt\)/)
  assert.match(actionsSource, /selectSettingsQuickSaveSlot/)
  assert.match(actionsSource, /case "saveProgressSlot":[\s\S]*?type: "saveToSlot"/)
  assert.match(settingsPanelSource, /listProgressSaveSlots\(saveSlots\)/)
  assert.match(settingsPanelSource, /progressSaveSlots\.map/)
  assert.match(inputSource, /getLastActivityAt\(\): number/)
  assert.match(inputSource, /hasActiveInput\(\): boolean/)
  assert.match(appSource, /IdleAutoSaveOverlay/)
})

test("app state and command dispatch stay outside the composition root", () => {
  const hookSource = readProjectFile("apps/web/src/app/use-magnolia-app.ts")
  const appStateSource = readProjectFile("apps/web/src/app/app-state.ts")
  const actionsSource = readProjectFile("apps/web/src/app/magnolia-actions.ts")
  const frameLoopSource = readProjectFile("apps/web/src/app/frame-loop/use-magnolia-frame-loop.ts")
  const commandRunnerSource = readProjectFile("apps/web/src/app/session-command-runner.ts")
  const appModuleSources = [
    readProjectFile("apps/web/src/app/session-sync.ts"),
    readProjectFile("apps/web/src/app/magnolia-actions.ts"),
    readProjectFile("apps/web/src/app/idle-auto-save.ts"),
    readProjectFile("apps/web/src/app/presentation-timers.ts"),
    readProjectFile("apps/web/src/app/frame-loop/use-magnolia-frame-loop.ts"),
  ]

  assert.match(appStateSource, /export type MagnoliaAppState =/)
  assert.match(appStateSource, /equipmentGuideTargetId: string \| null/)
  assert.doesNotMatch(hookSource, /export type MagnoliaAppState =/)
  for (const source of appModuleSources) {
    assert.doesNotMatch(source, /from "@\/app\/use-magnolia-app"/)
  }

  assert.match(commandRunnerSource, /export async function dispatchAndSync/)
  assert.match(commandRunnerSource, /command\.type !== "openMap"/)
  assert.match(commandRunnerSource, /createExplorePopup\("locked", "os magnolia が必要です。"\)/)
  assert.doesNotMatch(actionsSource, /await session\.dispatch/)
  assert.match(actionsSource, /dispatchAndSync/)
  assert.doesNotMatch(frameLoopSource, /session\.dispatch/)
  assert.match(frameLoopSource, /dispatchAndSync\(session, \{ type: "closePanel" \}/)
  assert.match(frameLoopSource, /dispatchAndSync\(session, \{ type: "openMap" \}/)
  assert.match(frameLoopSource, /dispatchAndSync\(session, \{ type: "openEquipment" \}/)
  assert.match(frameLoopSource, /readFirstEquipmentGuideTarget\(appState\)/)
  assert.match(frameLoopSource, /writeSeenEquipmentToStorage/)
  assert.match(actionsSource, /clearEquipmentGuideIfTarget/)
})

test("scan key defaults and prompts use Space", () => {
  const settingsSource = readProjectFile("packages/contracts/src/settings.ts")
  const inputSource = readProjectFile("apps/web/src/app/use-magnolia-input.ts")
  const exploreScreenSource = readProjectFile("apps/web/src/screens/explore/ExploreScreen.tsx")

  assert.match(settingsSource, /scan: "Space"/)
  assert.match(settingsSource, /current\.scan === "KeyR" \? DEFAULT_KEYBINDINGS\.scan : current\.scan/)
  assert.match(inputSource, /const SCAN_FALLBACK_CODES = \["Space"\]/)
  assert.match(inputSource, /const PRIMARY_ACTION_FALLBACK_CODES = \["KeyZ"\]/)
  assert.match(inputSource, /const SECONDARY_ACTION_FALLBACK_CODES = \["KeyX"\]/)
  assert.match(inputSource, /const EQUIPMENT_FALLBACK_CODES = \["KeyE", "Escape"\]/)
  assert.match(inputSource, /isPrimaryActionPressed\(settings: SettingsRow\)/)
  assert.match(inputSource, /isSecondaryActionPressed\(settings: SettingsRow\)/)
  assert.match(inputSource, /isPrimaryActionJustPressed\(settings: SettingsRow\)/)
  assert.match(inputSource, /isSecondaryActionJustPressed\(settings: SettingsRow\)/)
  assert.match(exploreScreenSource, /<ControlHelpRow label="connect" keys=\{\["Enter", "左クリック", "Z"\]\}/)
  assert.match(exploreScreenSource, /keys=\{\["Space", "右クリック", "X"\]\}/)
  assert.match(exploreScreenSource, /<ControlHelpRow label="equipment" keys=\{\["E", "Esc"\]\}/)
  assert.match(exploreScreenSource, /keys=\{\["WASD", "↑←↓→"\]\}/)
  assert.match(exploreScreenSource, /TutorialIconCallout/)
  assert.match(exploreScreenSource, /showOsMagnoliaEquipPrompt/)
  assert.match(exploreScreenSource, /os magnoliaを装備してください/)
  assert.match(exploreScreenSource, /ehud--signal-prompt/)
  assert.match(exploreScreenSource, /FIRST_MISSION_TUTORIAL_NODE_ID = "node_tx_good_morning"/)
  assert.match(exploreScreenSource, /visibleTransmission\?\.state === "complete"/)
  assert.match(exploreScreenSource, /keyLabel=\{\["Enter", "左クリック", "Z"\]\}/)
  assert.match(exploreScreenSource, /keyLabel=\{\["Space", "右クリック", "X"\]\}/)
  assert.match(exploreScreenSource, /ariaLabel="Space、右クリック、X でスキャンを出します"/)
  assert.doesNotMatch(exploreScreenSource, /ariaLabel="press E or Escape to open equipment"/)
  assert.match(exploreScreenSource, /ariaLabel="Enter、左クリック、Z で mission 01 を開始します"/)
  assert.match(exploreScreenSource, /keyLabel=\{\["Space", "右クリック", "X"\]\}[\s\S]*?tone="warm"/)
  assert.match(exploreScreenSource, /placement=\{shipPromptPlacement\}[\s\S]*?keyLabel=\{\["Space", "右クリック", "X"\]\}/)
})

test("battle start tutorial icons show main and sub input near the ship", () => {
  const appStateSource = readProjectFile("apps/web/src/app/app-state.ts")
  const sessionSyncSource = readProjectFile("apps/web/src/app/session-sync.ts")
  const appSource = readProjectFile("apps/web/src/app/App.tsx")
  const battleScreenSource = readProjectFile("apps/web/src/screens/battle/BattleScreen.tsx")
  const battleStyleSource = readProjectFile("apps/web/src/styles/battle.css")
  const promptSource = readProjectFile("apps/web/src/components/InteractionPrompt.tsx")

  assert.match(promptSource, /export function TutorialIconCallout/)
  assert.match(promptSource, /formatTutorialIconAnchorOffset/)
  assert.match(appStateSource, /export type BattleTutorialIconState/)
  assert.match(appStateSource, /battleTutorialIconState: BattleTutorialIconState \| null/)
  assert.match(sessionSyncSource, /function reduceBattleTutorialIconState/)
  assert.match(sessionSyncSource, /playerMainWeaponFired[\s\S]*?playerMainMeleeUsed/)
  assert.match(sessionSyncSource, /playerSubWeaponUsed[\s\S]*?playerBarrierStarted/)
  assert.match(appSource, /battleTutorialIconState=\{app\.battleTutorialIconState\}/)
  assert.match(battleScreenSource, /BATTLE_START_TUTORIAL_ICON_MS = 6000/)
  assert.match(battleScreenSource, /shouldShowMainTutorialIcon[\s\S]*?!battleTutorialIconState\?\.mainUsed/)
  assert.match(battleScreenSource, /shouldShowSubTutorialIcon[\s\S]*?!battleTutorialIconState\?\.subUsed/)
  assert.match(battleScreenSource, /readBattleTutorialIconAnchor\(renderState\.player\.position\)/)
  assert.match(battleScreenSource, /placement="left-up"[\s\S]*?keyLabel=\{\["左クリック", "Z"\]\}[\s\S]*?label="main"/)
  assert.match(battleScreenSource, /placement="right-up"[\s\S]*?keyLabel=\{\["右クリック", "X"\]\}[\s\S]*?label="sub"/)
  assert.match(battleScreenSource, /main — 左クリック \/ z/)
  assert.match(battleScreenSource, /sub — 右クリック \/ x/)
  assert.match(battleScreenSource, /tone="danger"[\s\S]*?className="battle-return-to-explore"/)
  assert.match(battleStyleSource, /battle-return-to-explore\.action-button[\s\S]*?var\(--mg-red\)/)
  assert.match(battleStyleSource, /battle-screen__canvas-wrap/)
  assert.match(battleStyleSource, /battle-tutorial-icons/)
})

test("scan cooldown meter uses session ratio and completion flash state", () => {
  const exploreCanvasSource = readProjectFile("apps/web/src/render/explore/ExploreCanvas.tsx")
  const exploreFrameSource = readProjectFile("apps/web/src/render/explore/draw-explore-frame.ts")
  const exploreRendererSource = readProjectFile("apps/web/src/render/explore/explore-scene-renderer.ts")
  const mapRendererSource = readProjectFile("apps/web/src/render/map/map-renderer.ts")
  const miniMapRendererSource = readProjectFile("apps/web/src/render/map/minimap-renderer.ts")
  const scanMeterSource = readProjectFile("apps/web/src/render/explore/scan-cooldown-meter.ts")
  const exploreScreenSource = readProjectFile("apps/web/src/screens/explore/ExploreScreen.tsx")
  const exploreStyleSource = readProjectFile("apps/web/src/styles/explore.css")

  assert.match(exploreCanvasSource, /createScanCooldownMeterState/)
  assert.match(exploreCanvasSource, /scanMeterStateRef/)
  assert.match(exploreFrameSource, /scanMeterState: refs\.scanMeterStateRef\.current/)
  assert.match(exploreRendererSource, /drawScanCooldownMeter/)
  assert.match(exploreRendererSource, /height: input\.height/)
  assert.match(exploreRendererSource, /ratio: input\.renderState\.scanCooldownRatio/)
  assert.match(exploreRendererSource, /drawTransmissionMarker\([\s\S]*?size: 17/)
  assert.match(mapRendererSource, /size: isSelected \? 16 : 13/)
  assert.match(mapRendererSource, /radius: 22/)
  assert.match(miniMapRendererSource, /size: 6\.2/)
  assert.match(scanMeterSource, /SCAN_METER_FLASH_MS = 520/)
  assert.match(scanMeterSource, /wasCoolingDown/)
  assert.match(scanMeterSource, /flashUntilMs = input\.timeMs \+ SCAN_METER_FLASH_MS/)
  assert.match(scanMeterSource, /drawCompletionGlow/)
  assert.match(exploreScreenSource, /explore-click-ripple/)
  assert.match(exploreStyleSource, /@keyframes explore-click-ripple/)
  assert.match(exploreScreenSource, /onSetMoveTarget/)
  assert.match(exploreScreenSource, /readExploreTargetAtPoint/)
  assert.match(exploreScreenSource, /readNearbyInteractTarget\(renderState, overlayFrame\) \?\? readExploreTargetAtPoint/)
  assert.match(exploreScreenSource, /NEARBY_ICON_INTERACT_RADIUS_PX = 72/)
  assert.match(exploreScreenSource, /target\.clickable \|\| target\.clickDistance <= NEARBY_ICON_INTERACT_RADIUS_PX/)
  assert.doesNotMatch(exploreScreenSource, /!hitTarget\.clickable/)
  assert.match(exploreScreenSource, /readOverlayInteractionCaptureRadius/)
  assert.match(exploreScreenSource, /TRANSMISSION_ICON_CAPTURE_RADIUS_PX = 64/)
  assert.match(exploreScreenSource, /NAV_CUE_CAPTURE_RADIUS_PX = 42/)
  assert.match(exploreScreenSource, /readNavCueCapturePoint/)
  assert.match(exploreScreenSource, /clickDistance: Math\.hypot/)
  assert.match(exploreScreenSource, /overlayPointToWorld/)
})

test("frontend phase 2 boundaries are enforced in source", () => {
  const exploreCanvasSource = readProjectFile("apps/web/src/render/explore/ExploreCanvas.tsx")
  const exploreFrameSource = readProjectFile("apps/web/src/render/explore/draw-explore-frame.ts")
  const mapScreenSource = readProjectFile("apps/web/src/screens/map/MapScreen.tsx")
  const mapRendererSource = readProjectFile("apps/web/src/render/map/map-renderer.ts")
  const miniMapSource = readProjectFile("apps/web/src/components/MiniMap.tsx")
  const miniMapRendererSource = readProjectFile("apps/web/src/render/map/minimap-renderer.ts")
  const menuScreenSource = readProjectFile("apps/web/src/screens/menu/MenuScreen.tsx")
  const menuStyleSource = readProjectFile("apps/web/src/styles/menu-equipment.css")
  const equipmentPanelSource = readProjectFile("apps/web/src/screens/menu/EquipmentPanel.tsx")
  const archivePanelSource = readProjectFile("apps/web/src/screens/menu/ArchivePanel.tsx")
  const battlePresentationSource = readProjectFile("apps/web/src/render/battle/presentation-layer.ts")
  const battleScreenSource = readProjectFile("apps/web/src/screens/battle/BattleScreen.tsx")
  const battleStyleSource = readProjectFile("apps/web/src/styles/battle.css")

  assert.ok(exploreCanvasSource.split("\n").length <= 500)
  assert.doesNotMatch(exploreCanvasSource, /function worldToCanvas|function isCanvasPointVisible/)
  assert.match(exploreCanvasSource, /drawExploreFrame/)
  assert.match(exploreFrameSource, /drawExploreScene/)
  assert.match(mapScreenSource, /drawMapCanvas/)
  assert.doesNotMatch(mapScreenSource, /function drawMapCanvas|#[0-9a-fA-F]{3,8}/)
  assert.match(mapRendererSource, /drawArtificialGrid/)
  assert.match(mapRendererSource, /drawSignalPulse/)
  assert.match(miniMapSource, /drawMiniMapFrame/)
  assert.match(miniMapSource, /useCanvasAnimationLoop/)
  assert.match(miniMapRendererSource, /canvas-palette/)

  assert.match(menuScreenSource, /menuViewModel: MenuViewModel/)
  assert.match(menuScreenSource, /menu-click-glitch/)
  assert.match(menuScreenSource, /onPointerDown/)
  assert.match(menuScreenSource, /role="tablist"/)
  assert.match(menuScreenSource, /`menu-tab--\$\{tab\}`/)
  assert.match(menuStyleSource, /menu-tab--archive/)
  assert.match(menuStyleSource, /menu-tab--archive\.menu-tab--active/)
  assert.match(menuScreenSource, /tab === "equipment"[\s\S]*?audioEvents\.equipmentPanelOpen\(\)/)
  assert.match(menuScreenSource, /audioEvents\.equipmentArchiveCategorySelect\(\)/)
  assert.match(menuScreenSource, /onUnequip=/)
  assert.match(menuScreenSource, /setSelectedCategory\(guidedCategory\)/)
  assert.match(menuScreenSource, /setSelectedEquipmentId\(equipmentGuideTargetId\)/)
  assert.match(equipmentPanelSource, /viewModel: EquipmentPanelViewModel/)
  assert.doesNotMatch(equipmentPanelSource, /equipmentGuideTargetId/)
  assert.match(equipmentPanelSource, /onUnequip/)
  assert.match(equipmentPanelSource, />\s*装備解除\s*</)
  assert.doesNotMatch(menuStyleSource, /equip-cat--guide/)
  assert.doesNotMatch(menuStyleSource, /list-card--guide/)
  assert.doesNotMatch(menuStyleSource, /equip-detail__equip-action--guide/)
  assert.match(menuStyleSource, /equip-detail__action-list/)
  assert.match(menuStyleSource, /equip-detail__unequip-action/)
  assert.match(archivePanelSource, /viewModel: ArchiveViewModel/)
  assert.doesNotMatch(equipmentPanelSource, /ContentBundle|ProfileAggregate|unlockSource|levelParams/)
  assert.doesNotMatch(archivePanelSource, /ContentBundle|ProfileAggregate|hasVisibleArchiveContent/)

  assert.match(battlePresentationSource, /case "battle\.mission\.beat":/)
  assert.match(battlePresentationSource, /intentTag/)
  assert.match(battleScreenSource, /readMissionBeatSubtitleTone/)
  assert.match(battleScreenSource, /demoClearProgressLabel/)
  assert.match(battleScreenSource, /battle-result-overlay__demo-progress/)
  assert.match(battleScreenSource, /体験版：クリア済み\$\{resultViewModel\.demoClearProgress\.clearedMissionCount\}\/\$\{resultViewModel\.demoClearProgress\.totalMissionCount\}/)
  assert.match(battleStyleSource, /battle-result-overlay__demo-progress/)
})

test("presentation reducer dedupes request ids and prunes expired events", () => {
  const reducerSource = readProjectFile("apps/web/src/app/presentation/presentation-reducer.ts")

  assert.match(reducerSource, /const knownRequestIds = collectKnownRequestIds\(pruned\)/)
  assert.match(reducerSource, /knownRequestIds\.has\(request\.requestId\)/)
  assert.match(reducerSource, /knownRequestIds\.add\(request\.requestId\)/)
  assert.match(reducerSource, /battleEvents: current\.battleEvents\.filter\(\(event\) => event\.expiresAt > now\)/)
  assert.match(reducerSource, /transitionEvents: current\.transitionEvents\.filter\(\(event\) => event\.expiresAt > now\)/)
})

test("audio acceptance path has one settings source and optional asset guards", () => {
  const audioHubSource = readProjectFile("apps/web/src/audio/AudioHub.ts")
  const audioEventsSource = readProjectFile("apps/web/src/audio/audioEvents.ts")
  const audioControllerSource = readProjectFile("apps/web/src/app/audio-controller.ts")
  const audioAdapterSource = readProjectFile("apps/web/src/app/audio-event-adapter.ts")
  const appSource = readProjectFile("apps/web/src/app/App.tsx")
  const frameLoopSource = readProjectFile("apps/web/src/app/frame-loop/use-magnolia-frame-loop.ts")
  const presentationTimersSource = readProjectFile("apps/web/src/app/presentation-timers.ts")
  const soundCatalogSource = readProjectFile("apps/web/src/audio/soundCatalog.ts")
  const sessionTypesSource = readProjectFile("packages/contracts/src/session-types.ts")
  const battleStepSource = readProjectFile("packages/game-session/src/battle/step-battle.ts")

  assert.doesNotMatch(audioHubSource, /localStorage|AUDIO_SETTINGS_STORAGE_KEY|setVolume\(|toggleMuted\(|subscribe\(/)
  assert.match(audioControllerSource, /audioHub\.applyMixerGains\(createAudioMixerGains\(settings\)\)/)
  assert.match(audioControllerSource, /SETTINGS_VOLUME_STEPS/)
  assert.match(appSource, /initializeGameAudio\(\)/)
  assert.match(audioAdapterSource, /playSessionAudioEvents/)
  assert.match(audioAdapterSource, /playerMainWeaponFired/)
  assert.match(audioAdapterSource, /playerMainMeleeUsed[\s\S]*?audioEvents\.playerMelee\(\)/)
  assert.match(audioAdapterSource, /enemyProjectileFired[\s\S]*?audioEvents\.enemyShot\(\)/)
  assert.match(audioAdapterSource, /playedPresentationRequestIds/)
  assert.match(audioAdapterSource, /"equipment"/)
  assert.match(audioAdapterSource, /!previousWasMenu && nextIsMenu[\s\S]*?audioEvents\.uiOpen\(\)/)
  assert.match(audioAdapterSource, /previousScreen === "explore" && nextSnapshot\.screen === "equipment"[\s\S]*?audioEvents\.equipmentPanelOpen\(\)/)
  assert.match(audioAdapterSource, /runtimeHandlerId === "sub\.field\.silent_wave"[\s\S]*?audioEvents\.silentWave\(\)/)
  assert.match(audioAdapterSource, /syncTransmissionVoicePlayback/)
  assert.match(audioAdapterSource, /transmissionAudio/)
  assert.match(audioHubSource, /syncTransmissionVoice\(options: TransmissionVoiceSyncOptions\)/)
  assert.match(audioHubSource, /driftToleranceMs/)
  assert.match(frameLoopSource, /pauseTransmissionVoice\(\)/)
  assert.match(frameLoopSource, /snapshot\.screen === "explore"[\s\S]*?runExploreFrame/)
  assert.match(frameLoopSource, /explorationMoveAudioPlayingRef/)
  assert.match(frameLoopSource, /function startExplorationMoveAudio\(\)[\s\S]*?audioEvents\.explorationMoveStart\(\{ fadeMs: MOVEMENT_AUDIO_START_FADE_MS \}\)/)
  assert.match(frameLoopSource, /function stopExplorationMoveAudio\(fadeMs = MOVEMENT_AUDIO_STOP_FADE_MS\)[\s\S]*?audioEvents\.explorationMoveStop\(fadeMs\)/)
  assert.match(frameLoopSource, /snapshot\.screen === "battle"[\s\S]*?stopExplorationMoveAudio\(MOVEMENT_AUDIO_INTERRUPT_FADE_MS\)/)
  assert.match(presentationTimersSource, /activeOverlay\?\.cueId !== REBOOT_SEQUENCE_CUE_ID/)
  assert.match(presentationTimersSource, /audioEvents\.reconstructionStarted\(\)/)
  assert.match(sessionTypesSource, /type: "playerMainWeaponFired"[\s\S]*?runtimeHandlerId\?: string/)
  assert.match(sessionTypesSource, /type: "playerMainMeleeUsed"/)
  assert.match(sessionTypesSource, /type: "playerSubWeaponUsed"[\s\S]*?runtimeHandlerId\?: string/)
  assert.match(sessionTypesSource, /type: "playerBarrierStarted"[\s\S]*?runtimeHandlerId\?: string/)
  assert.match(battleStepSource, /events\.push\(\{ type: "playerMainWeaponFired", \.\.\.mainEventContext \}\)/)
  assert.match(battleStepSource, /\.\.\.spawnedEffects\.events/)
  assert.match(battleStepSource, /runtimeHandlerId: subHandlerId/)
  assert.match(battleStepSource, /type: "playerBarrierStarted", \.\.\.subEventContext/)
  assert.match(battleStepSource, /type: "playerSubWeaponUsed", \.\.\.subEventContext/)

  assert.match(soundCatalogSource, /PLACEHOLDER_SHOT_WAV_URL = '\/sound\/placeholder\/shot-placeholder\.wav'/)
  assert.doesNotMatch(soundCatalogSource, /new URL\(|sound\/ショット/)
  assert.ok(!fs.existsSync(path.join(rootDir, "apps/web/public/sound/shot-placeholder.wav")))
  assert.ok(!fs.existsSync(path.join(rootDir, "apps/web/public/sound/placeholder/shot-placeholder.md")))
  assert.ok(!fs.existsSync(path.join(rootDir, "sound/sound-inventory-v3.md")))
  assert.ok(!fs.existsSync(path.join(rootDir, "sound/ショット.wav")))
  assert.ok(!fs.existsSync(path.join(rootDir, "apps/web/public/sound/mp3/title_select.wav")))

  assert.match(audioHubSource, /if \(asset\.optional\) \{\s*continue;\s*\}/)
  assert.match(audioHubSource, /private tryPlayAudio\(audio: HTMLAudioElement/)
  assert.match(audioHubSource, /catch \(error\) \{\s*onFailure\(error\);\s*return false;\s*\}/)
  assert.match(audioHubSource, /sourceGain \* masterVolume \* channelVolume/)
  assert.match(soundCatalogSource, /sourceGain: number/)
  assert.doesNotMatch(soundCatalogSource, /defaultVolume/)
  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.UI_OPEN, 'ui', 0\.34/)
  assert.match(audioEventsSource, /equipmentPanelOpen\(\): void \{[\s\S]*?audioHub\.play\(SOUND_KEYS\.UI_OPEN, \{ volume: 0\.56 \}\)/)
  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.UI_CONFIRM, 'ui', 0\.44/)
  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.UI_MENU_UP, 'ui', 0\.34/)
  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.UI_CANCEL, 'ui', 0\.38/)
  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.TITLE_NEW_GAME, 'ui', 0\.6/)
  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.TITLE_LOAD_GAME, 'ui', 0\.56/)
  assert.match(audioEventsSource, /playerMelee\(options\?: PlaySoundOptions\): void \{[\s\S]*?volume: 0\.58/)
  assert.match(soundCatalogSource, /asset\(SOUND_ASSET_IDS\.PLAYER_MELEE, 'combat\/main-melee\.wav'/)
  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.COMBAT_PLAYER_MELEE, 'sfx', 0\.24/)
  assert.match(soundCatalogSource, /asset\(SOUND_ASSET_IDS\.ENEMY_SHOT, 'combat\/enemy-shot\.mp3'/)
  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.COMBAT_ENEMY_SHOT, 'sfx', 0\.08/)
  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.COMBAT_PLAYER_HIT, 'sfx', 0\.24/)
  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.COMBAT_PLAYER_HIT_HEAVY, 'sfx', 0\.22/)
  assert.match(soundCatalogSource, /asset\(SOUND_ASSET_IDS\.SYSTEM_RECONSTRUCT, 'system\/reconstruct\.wav'/)
  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.SYSTEM_RECONSTRUCT, 'sfx', 0\.56/)
  assert.match(soundCatalogSource, /asset\(SOUND_ASSET_IDS\.EXPLORE_MOVE, 'explore\/move\.wav'/)
  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.EXPLORE_MOVE, 'sfx', 0\.16[\s\S]*?loop: true/)
  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.EQUIPMENT_ARCHIVE_CATEGORY_SELECT, 'ui', 0\.4/)
  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.EQUIPMENT_SILENT_WAVE, 'sfx', 0\.48/)
  assert.match(soundCatalogSource, /asset\(SOUND_ASSET_IDS\.BARRIER_UP, 'equipment\/noise_camceler\.wav'/)
  assert.match(audioHubSource, /asset\?\.optional && !isAutoplayError\(error\)/)
  assert.match(audioHubSource, /markOptionalAssetUnavailable\(asset\)/)
  assert.match(audioHubSource, /unavailableAssetIds\.has\(definition\.assetId\)/)

  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.BGM_TITLE, 'bgm', 0\.32/)
  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.BGM_EXPLORATION, 'bgm', 0\.29/)
  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.BGM_COMBAT, 'bgm', 0\.32/)
  assert.match(soundCatalogSource, /readyEvent\(SOUND_KEYS\.NOISE_RADIO_STATIC/)
  assert.doesNotMatch(soundCatalogSource, /placeholderEvent\(/)
  assert.doesNotMatch(soundCatalogSource, /missingEvent\(SOUND_KEYS\.(BGM_TITLE|NOISE_RADIO_STATIC|BARRIER_LOOP|COMBAT_ENEMY_SHOT)\)/)
  assert.match(soundCatalogSource, /const missingEvent[\s\S]*?undefined, options\)/)

  const requiredSoundFiles = [
    ...soundCatalogSource.matchAll(/asset\(SOUND_ASSET_IDS\.[A-Z0-9_]+, '([^']+\.(?:wav|mp3))'/g),
  ].map((match) => match[1])
  assert.equal(requiredSoundFiles.length, 44)
  assert.ok(
    requiredSoundFiles.every((filename) => filename.includes("/")),
    "sound assets should be grouped under category directories",
  )
  assert.ok(requiredSoundFiles.includes("ui/ui-panel-open.wav"))
  assert.ok(requiredSoundFiles.includes("ui/ui-panel-close.wav"))
  assert.ok(requiredSoundFiles.includes("title/op.wav"))
  assert.ok(requiredSoundFiles.includes("combat/main-melee.wav"))
  assert.ok(requiredSoundFiles.includes("combat/enemy-shot.mp3"))
  assert.ok(requiredSoundFiles.includes("system/reconstruct.wav"))
  assert.ok(!requiredSoundFiles.includes("bgm/bgm-title.wav"))
  assert.ok(requiredSoundFiles.includes("explore/scan.wav"))
  assert.ok(!requiredSoundFiles.includes("explore/explore-scan.wav"))
  assert.ok(requiredSoundFiles.includes("explore/move.wav"))
  assert.ok(requiredSoundFiles.includes("equipment/noise_camceler.wav"))
  assert.ok(requiredSoundFiles.includes("equipment/static_waves.wav"))
  assert.ok(requiredSoundFiles.every((filename) => /\.(?:wav|mp3)$/.test(filename)))
  for (const filename of requiredSoundFiles) {
    const guidePath = path.join(rootDir, "apps/web/public/sound", filename.replace(/\.(?:wav|mp3)$/, ".md"))
    assert.ok(!fs.existsSync(guidePath), `${filename} should not keep a sidecar markdown guide`)
  }
  assert.match(soundCatalogSource, /title-new-game\.wav/)
  assert.match(soundCatalogSource, /title-load-game\.wav/)
  assert.ok(fs.existsSync(path.join(rootDir, "apps/web/public/sound/title/title-new-game.wav")))
  assert.ok(fs.existsSync(path.join(rootDir, "apps/web/public/sound/title/title-load-game.wav")))
  assert.ok(fs.existsSync(path.join(rootDir, "apps/web/public/sound/combat/main-melee.wav")))
  assert.ok(fs.existsSync(path.join(rootDir, "apps/web/public/sound/combat/enemy-shot.mp3")))
  assert.ok(fs.existsSync(path.join(rootDir, "apps/web/public/sound/system/reconstruct.wav")))
  assert.match(soundCatalogSource, /equipment-archive-category-select\.wav/)
  assert.match(soundCatalogSource, /player-hit-heavy\.wav/)
})

function readProjectFile(relativePath) {
  return fs.readFileSync(path.join(rootDir, relativePath), "utf8")
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}
